openapi: 3.0.0
info:
  title: CaseWorx API - Document Domain
  description: |
    [CaseWorx](https://app.caseworx-baurecht.de/) API - Document Domain describing components of the case  
  version: 0.1.0
  contact: 
    name: Wolters Kluwer Deutschland GmbH
    url: https://www.caseworx-baurecht.de/informationen/kontakt
    email: caseworx@wolterskluwer.com
  license:
    name: GNU Affero General Public License version 3
    url: https://www.gnu.org/licenses/agpl-3.0.html

components:
  schemas:
    DocumentState:
      description: State of the document in the document lifecycle
      readOnly: true
      type: string
      enum:
        - original
        - unified
        - autoenriched
        - enriched
        - annotated
      example: original

    DocumentRaw:
      description: Properties of original (not enriched) document 
      type: object
      required:
        - id
        - state
        - filename
      properties:
        id:
          description: Internal ID of the document
          type: integer
          format: int64
          minimum: 0
          readOnly: true
          example: 67890
        state:
          $ref: '#/components/schemas/DocumentState'
        filename:
          description: Filename under which the document's media have been registered during upload
          type: string
          readOnly: true
          example: 'mySampleFile.pdf'
        created:
          description: Document creation timestamp
          type: string
          format: date-time
          readOnly: true
          example: '2020-01-18T18:00:00Z'
        updated:
          description: Document last update timestamp
          type: string
          format: date-time
          readOnly: true
          example: '2020-01-18T18:00:00Z'

    Document:
      description: Properties of an enriched document resource
      allOf:
        - $ref: '#/components/schemas/DocumentRaw'
        - type: object
          description: Properties of a document resource
          required:
            - title
            - date
            - types
          properties:
            id:
              description: Internal ID of the document
              type: integer
              readOnly: true
              example: 67890
            filename:
              description: Filename under which the document's media have been registered during upload
              type: string
              readOnly: true
              example: 'mySampleFile.pdf'
            created:
              description: Document creation timestamp
              type: string
              format: date-time
              readOnly: true
              example: '2020-01-18T18:00:00Z'
            updated:
              description: Document last update timestamp
              type: string
              format: date-time
              readOnly: true
              example: '2020-01-18T18:00:00Z'
            title:
              description: Document title / Dokumenttitel
              type: string
              minLength: 1
              example: 'My test document title'
            date:
              description: Document date coordinate in the case timeline / Datum
              type: string
              format: date
              example: '2019-12-01'
            types:
              description: |
                A collection of document types / Dokumententyp  
                A document requires minimum one type. Types must be unique.  
              type: array
              items:
                type: string
                minLength: 1
              uniqueItems: true
              minItems: 1
              maxItems: 500
              example:
                - 'Fax'
                - 'Complaint'
            parties:
              description: |
                A collection of parties associated with a document / Beteiligte  
                Parties must be unique.
              type: array
              items:
                type: string
                minLength: 1
              uniqueItems: true
              maxItems: 500
              example:
                - 'John Doe'
                - 'Acme Corp.'
            trades:
              description: |
                A collection of technical trades associated with a document / Gewerk  
                Trades must be unique.
              type: array
              items:
                type: string
                minLength: 1
              uniqueItems: true
              maxItems: 500
              example:
                - 'plumbing'
                - 'masonery'
            defects:
              description: |
                A collection of defects associated with a document / Mängel  
                Defects must be unique.
              type: array
              items:
                type: integer
                minLength: 1
              uniqueItems: true
              maxItems: 500
              example:
                - 122562
                - 122680
            tags:
              description: |
                A collection of tags associated with a document / Eigene Schlagworte  
                Tags must be unique.
              type: array
              items:
                type: string
                minLength: 1
              uniqueItems: true
              maxItems: 500
              example:
                - 'to do'
                - 'easy win'
            suggestions:
              description: Automatically recognized values of document metadata
              type: object
              properties:
                defects:
                  description: |
                    A collection of defects associated with a document / Mängel  
                    Defects must be unique.
                  type: object
                  properties:
                    descriptions:
                      type: array
                      items:
                        type: string
                      uniqueItems: true
                      maxItems: 500
                    identifiers:
                      type: array
                      items:
                        type: string
                      uniqueItems: true
                      maxItems: 500
                    refs:
                      description: An array of references to defect identifiers 
                      type: array
                      items:
                        type: integer
                      uniqueItems: true
                      maxItems: 500
                  items:
                    type: string
                    minLength: 1
                  uniqueItems: true
                  maxItems: 500
                  example:
                    descriptions:
                      - Mangel Nr. 122562
                      - Mangel Nr. 122680
                    identifiers:
                      - "122562"
                      - "122680"
                    refs:
                      - 12345
                      - 67890

  parameters:
    DocumentId:
      name: documentId
      description: Document identifier
      in: path
      required: true
      schema:
        type: integer
        format: int64
        minimum: 0
      example: 67890
  
  responses:
    DocumentMetadataOK:
      description: Returns properties of a document
      headers:
        x-cwx-cid:
          $ref: 'cwx-commons-domain.yaml#/components/headers/x-cwx-cid'
      content:
        application/json:
          schema:
            anyOf:
              - $ref: '#/components/schemas/DocumentRaw'
              - $ref: '#/components/schemas/Document'
          examples:
            raw:
              $ref: '#/components/examples/RawDocumentMetadata'
            enriched:
              $ref: '#/components/examples/EnrichedDocumentMetadata'
    
    DocumentMetadataListOK:
      description: Returns an array of documents in a case with available properties
      headers:
        x-cwx-cid:
          $ref: 'cwx-commons-domain.yaml#/components/headers/x-cwx-cid'
      content:
        application/json:
          schema:
            type: array
            items:
              anyOf:
                - $ref: '#/components/schemas/DocumentRaw'
                - $ref: '#/components/schemas/Document'
          examples:
            list:
              $ref: '#/components/examples/DocumentMetadataList'
  
  examples:
    RawDocumentMetadata:
      description: Document metadata when the document is in unenriched state of the life cycle
      value: 
        id: 12345
        state: original
        filaneme: myFile.pdf
        
    EnrichedDocumentMetadata:
      description: Document metadata when the document is in enriched state of the life cycle
      value: 
        id: 67890
        state: enriched
        filaneme: myAnoterFile.pdf
        title: My test document title
        date: 2019-12-02
        types:
          - 'Fax'
          - 'Complaint'
        parties:
          - 'John Doe'
          - 'Acme Corp.'
        trades:
          - 'plumbing'
          - 'masonery'
        defects:
          - 122562
          - 122680
        tags:
          - 'to do'
          - 'easy win'
        suggestions:
          descriptions:
            - Mangel Nr. 122562
            - Mangel Nr. 122680
          identifiers:
            - "122562"
            - "122680"
          refs:
            - 12345
            - 67890
    
    DocumentMetadataList:
      description: List of document entities with their properties
      value: 
        - id: 12345
          state: original
          filaneme: myFile.pdf
        - id: 67890
          state: enriched
          filaneme: myAnoterFile.pdf
          title: My test document title
          date: 2019-12-02
          types:
            - 'Fax'
            - 'Complaint'
          parties:
            - 'John Doe'
            - 'Acme Corp.'
          trades:
            - 'plumbing'
            - 'masonery'
          defects:
            - 122562
            - 122680
          tags:
            - 'to do'
            - 'easy win'
          suggestions:
            descriptions:
              - Mangel Nr. 122562
              - Mangel Nr. 122680
            identifiers:
              - "122562"
              - "122680"
            refs:
              - 12345
              - 67890