openapi: 3.0.0
info:
  title: CaseWorx API - Commons Domain
  description: |
    [CaseWorx](https://app.caseworx-baurecht.de/) API - Commons Domain describing shared components of the API
  version: "0.1.0"
  contact: 
    name: Wolters Kluwer Deutschland GmbH
    url: https://www.caseworx-baurecht.de/informationen/kontakt
    email: caseworx@wolterskluwer.com
  license:
    name: GNU Affero General Public License version 3
    url: https://www.gnu.org/licenses/agpl-3.0.html

components:
  schemas:
    UniversalId:
      description: Universal ID to be used unless specific validation restrictions are needed
      type: string
      maxLength: 50
      example: b50ef924-2c29-4097-904b-ab2fb286e3bb
      
    ResourceId:
      description: Standard resource ID (case, document)
      type: integer
      format: int64
      minimum: 0
      example: 12345
      
    Error:
      description: Standard error object
      type: object
      properties:
        code:
          type: integer
          example: 100000
        message:
          type: string
          minLength: 1
          example: Something went wrong
        hint:
          type: string
          minLength: 1
          example: Fix the problem
      required: 
        - message

  parameters:
    CorrelationId:
      name: x-cwx-cid
      description: Correlation ID
      in: header
      required: false
      schema:
        $ref: '#/components/schemas/UniversalId'
      example: b50ef924-2c29-4097-904b-ab2fb286e3bb

  responses:
    Info202:
      description: |
        Resource not ready  
        Requested resource exists but it has not yet reached the state in its lifecycle where the requested criteria are satisfied. It may or may not reach this state in the future.  
        In requests changing state of a resource it means that the request has been accepted but not acted upon yet. It may or may not be in the future.
      headers:
        x-cwx-cid:
          $ref: '#/components/headers/x-cwx-cid'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'  # Error schema fits here, striclty speaking this is not an error
          example:
            code: 202001
            message: Requested media of the document resource {documentId} is not ready
            hint: Requested resource exists but it has not yet reached the state in its lifecycle where the requested criteria are satisfied. It may or may not reach this state in the future.
    Error400:
      description: |
        Bad request  
        All otherwise unhandled client-side errors. Check the request parameters.
      headers:
        x-cwx-cid:
          $ref: '#/components/headers/x-cwx-cid'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Error401:
      description: |
        Unauthorized  
        Check access token. The token might be invalid or might have expired.  
        Sent when the identity of the user cannot be established (including cases when the token cannot be trusted)
      headers:
        x-cwx-cid:
          $ref: '#/components/headers/x-cwx-cid'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Error403:
      description: |
        Forbidden  
        The user for whom the access token was issued cannot access requested resource. Check access rights of the user.  
        Sent when the identity of the user has been established and the user has not been granted permission to access the resource.
      headers:
        x-cwx-cid:
          $ref: '#/components/headers/x-cwx-cid'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Error404:
      description: |
        Not Found  
        Requested resource doesn't exist.  
        Check how do you obtain the resource IDsused. Case or document might have been deleted.
      headers:
        x-cwx-cid:
          $ref: '#/components/headers/x-cwx-cid'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Error429:
      description: |
        Too Many Requests  
        An indication that the client has exceeded its request quota. Upon catching such exceptions, the client can resubmit the failed request in a way that is rate limiting, while complying with the API throttling limits associated with its usage plan.  
    Error500:
      description: |
        Internal server error  
        All unhandled server-side errors
      headers:
        x-cwx-cid:
          $ref: '#/components/headers/x-cwx-cid'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  headers:
    x-cwx-cid:
      description: Correlation ID
      required: false
      schema:
        $ref: '#/components/schemas/UniversalId'
      example: b50ef924-2c29-4097-904b-ab2fb286e3bb