openapi: 3.0.0
info:
  title: CaseWorx API - Change Domain
  description: |
    [CaseWorx](https://app.caseworx-baurecht.de/) API - Change Domain describing shared components of the API
  version: 0.6.0
  contact: 
    name: Wolters Kluwer Deutschland GmbH
    url: https://www.caseworx-baurecht.de/informationen/kontakt
    email: caseworx@wolterskluwer.com
  license:
    name: GNU Affero General Public License version 3
    url: https://www.gnu.org/licenses/agpl-3.0.html

components:
  schemas:
    Change:
      description: |
        An object describing an atomic change to the state of the resource. This record should be interpreted as:  
        A _subject_ has performed an _action_ on an _object_  
        where:  
        _subject_ is indicated by `subId` (not delivered in the response)  
        _action_ is indicated by `action`  
        _object_ may be indicated by:  
        (`target`, `caseId`) if _object_ is a case  
        (`target`, `caseId`, `docId`) if _object_ is a document  
        (`target`, `caseId`, `docId`, `layer`) if _object_ is a document media  
        (`target`, `caseId`, `userId`) if _object_ is ACL  
      type: object
      required:
        - action
        - target
        - caseId
      properties:
        action:
          description: An indication of the type of change
          type: string
          enum:
            - create
            - delete
            - update
        target:
          description: Indicates which feature of a resource is affected by the change
          type: string
          enum:
            - metadata
            - media
            - acl
        layer:
          $ref: 'cwx-media-domain.yaml#/components/schemas/MediaLayer'
        caseId:
          $ref: 'cwx-commons-domain.yaml#/components/schemas/ResourceId'
        docId:
          $ref: 'cwx-commons-domain.yaml#/components/schemas/ResourceId'
        userId:
          $ref: 'cwx-commons-domain.yaml#/components/schemas/UniversalId'

    PageToken:
      $ref: 'cwx-commons-domain.yaml#/components/schemas/UniversalId'

    Changes:
      description: Response object containing next page token and list of changes
      type: object
      required:
        - nextPageToken
        - changes
      properties:
        nextPageToken:
          $ref: '#/components/schemas/PageToken'
        changes:
          description: List of changes that have occurred since the page token used in the request was generated
          type: array
          items:
            $ref: '#/components/schemas/Change'

  parameters:
    PageTokenQueryRef:
      name: pageToken
      description: The page token indicating temporal scope of the request
      in: query
      schema:
        $ref: '#/components/schemas/PageToken'

  responses:
    StartPageTokenOK:
      description: Returns start page token
      headers:
        x-cwx-cid:
          $ref: 'cwx-commons-domain.yaml#/components/headers/x-cwx-cid'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PageToken'

    ChangesOK:
      description: |
        Returns list of changes relevant for the user indicated by the access token in the timeframe indicated by 
        the page token. That is, the changes that occurred between the page token was generated and the request 
        resulting in this response has been received.
      headers:
        x-cwx-cid:
          $ref: 'cwx-commons-domain.yaml#/components/headers/x-cwx-cid'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Changes'
          examples:
            list:
              $ref: '#/components/examples/ChangesOK'

  pathitems:
    Changes:
      get:
        tags: 
          - changes
        description: |
          Returns a list of changes starting from the provided page token and the next page token.  
          Note that each resource maintains its own set of page tokens and they in principle cannot be used interchangeably.  
          Only a token received together with a response to poll all changes can be used when requesting a changes to a specific 
          resource.
        parameters: 
          - $ref: '#/components/parameters/PageTokenQueryRef'
          - $ref: 'cwx-commons-domain.yaml#/components/parameters/CorrelationId'
          - $ref: 'cwx-commons-domain.yaml#/components/parameters/ApiKey'
        responses:
          '200':
            $ref: '#/components/responses/ChangesOK'
          '400':
            $ref: 'cwx-commons-domain.yaml#/components/responses/Error400'
          '401':
            $ref: 'cwx-commons-domain.yaml#/components/responses/Error401'
          '403':
            $ref: 'cwx-commons-domain.yaml#/components/responses/Error403'
          '429':
            $ref: 'cwx-commons-domain.yaml#/components/responses/Error429'
          '500':
            $ref: 'cwx-commons-domain.yaml#/components/responses/Error500'

    StartPageToken:
      get:
        tags: 
          - changes
        description: |
          Returns start page token to navigate through changes.  
          Note that each resource maintains its own set of page tokens and they cannot be used interchangeably.  
          Only a token received together with a response to poll all changes can be used when requesting a changes to a specific 
          resource.
        parameters:
          - $ref: 'cwx-commons-domain.yaml#/components/parameters/CorrelationId'
          - $ref: 'cwx-commons-domain.yaml#/components/parameters/ApiKey'
        responses:
          '200':
            $ref: '#/components/responses/StartPageTokenOK'
          '400':
            $ref: 'cwx-commons-domain.yaml#/components/responses/Error400'
          '401':
            $ref: 'cwx-commons-domain.yaml#/components/responses/Error401'
          '403':
            $ref: 'cwx-commons-domain.yaml#/components/responses/Error403'
          '429':
            $ref: 'cwx-commons-domain.yaml#/components/responses/Error429'
          '500':
            $ref: 'cwx-commons-domain.yaml#/components/responses/Error500'

  examples:
    Change:
      description: Sample change record
      value:
        action: create
        target: media
        layer: original
        caseId: 12345
        docId: 67890
    
    ChangesOK:
      description: Sample response to a request for changes
      value:
        nextPageToken: djijndinwhywdmwk
        changes:
          - action: create
            target: metadata
            caseId: 12345
          - action: create
            target: media
            layer: original
            caseId: 12345
            docId: 67890
          - action: update
            target: acl
            caseId: 12345
            userId: hsi92dk9